---
title: "Stan_Testing"
output: pdf_document
date: "2023-08-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rstan through runStan.R

This report is based on the DEV_Test_StanR.R file.

```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(devtools)
library(ggplot2)
library(ggridges)
library(RColorBrewer)
library(gridExtra)
library(bridgesampling)
library(forcats)
library(rstan)
# install.packages("cmdstanr", repos = c('https://stan-dev.r-universe.dev', getOption("repos")))
library(cmdstanr)
library(bayesplot)
library(posterior)
library(MetricsCOSEWIC)
source(here::here("R/runStan.R"))
```

Sample data setup using the SebastesA sample dataset.

``` {r sample data setup, warning=FALSE, message=FALSE}
data <- read.csv(here::here("COSEWIC_WorkedExamples/MarineFish/Sebastes", "Sebastes_SampleData.csv"))
data.long <- data

# stk <- "DEV_TEST_SebastesA" # The name of the DU in question
stk <- "SebastesA"
gen <- 3
scenario.name <- "long-time-series" #"short-time-series"

yrs.window <- (3 * gen) + 1
calc.year <- 2021
du.df.long <- data.long %>% filter(DU == stk)

# Arithmetic smooth time-series (as in 2017 COSEWIC report on Fr sockeye)
du.df.long$Abd <- smoothSeries(du.df.long$Abd, gen=gen, filter.sides=1,
                               log.transform = FALSE, out.exp = FALSE,
                               na.rm=FALSE)

du.df.long <- du.df.long %>% mutate(logAbd=log(Abd))

# Shorten data set to years used to estimate trends
if(scenario.name == "short-time-series"){
  du.df <- du.df.long %>% filter(Year > (calc.year - yrs.window) &
                                   Year <= calc.year)
}
if(scenario.name == "long-time-series"){
  du.df <- du.df.long
}
```

run.stan input code

``` {r run stan}
stan.out <- run.stan(du.label = stk, 
                     du.df = du.df, 
                     yrs.window = yrs.window,
                     standardize.data = TRUE,
                     scenario.name = scenario.name,
                     prior_sigma_type = "exp")
```

run.stan output plots 

``` {r stan outputs}
# names(stan.out)
# [1] "pchange"         "probdecl"        "summary"         "slope.converged" "conv.details"    "samples"        
# [7] "fit.obj"         "logML"  

# stan.out$summary # Summary
# stan.out$fit.obj # stan.fit object
```

```{r plots}
# stan.out$pchange
# stan.out$probdecl
# stan.out$summary
# stan.out$slope.converged
# stan.out$samples

# test.df
# test.df.sub

# plotPattern(yrs = test.df$Year, vals = log(test.df$Spn),
#             width = 1, color = "darkblue",
#             yrs.axis = TRUE, vals.axis = TRUE,
#             #vals.lim=c(10,14),
#             hgrid = TRUE, vgrid = FALSE,
#             pch.val = 19, pch.bg = NULL)
# 
# addFit(data.df = test.df.sub, coeff = list(intercept = stan.out$summary["intercept","summary.50."],
#                                        slope = stan.out$summary["slope","summary.50."] )
# )
# 
# 
# plotPattern(yrs = test.df.sub$Year, vals = log(test.df.sub$Spn),
#             width = 1, color = "darkblue",
#             yrs.axis = TRUE, vals.axis = TRUE,
#             #vals.lim=c(10,14),
#             hgrid = TRUE, vgrid = FALSE,
#             pch.val = 19, pch.bg = NULL)
# 
# addFit(data.df = test.df.sub, coeff = list(intercept = stan.out$summary["intercept","summary.50."],
#                                            slope = vstan.out$summary["slope","summary.50."] )
# )
```

## JAGS through Module_calcPercChangeMCMC.R

```{r pressure, echo=FALSE, warning=FALSE, message=FALSE}
require(tidyverse)
require(rstanarm)
require(rstan)
require(shinystan)
require(coda)
library(MetricsCOSEWIC)
```

```{r sample data setup 2, warning=FALSE, message=FALSE}
# SR_Sample is a built in data set
# use '?SR_Sample' for more information
# ?SR_Sample
names(SR_Sample)
sort(unique(SR_Sample$Stock))
length(unique(SR_Sample$Stock))
head(SR_Sample)


# DU_SampleData is another built in data set
# ?DU_SampleData
names(DU_SampleData)
sort(unique(DU_SampleData$DU))
length(unique(DU_SampleData$DU))
head(DU_SampleData)

#  WRAPPER FUNCTION: multiFit FUNCTION
# run it on the SR data file
# data.in <- SR_Sample %>% select(Stock,Year,Spn) %>% rename(DU=Stock,Abd = Spn)
# head(data.in)

# run it on the DU sample data file
data.in <- DU_SampleData

# TESTING INDIVIDUAL FUNCTIONS
# Settings
stk <- "Stock3"
gen <- 4
yrs.do <- (3 * gen) +1
calc.yr <- 2017

test.df <- SR_Sample %>%
            dplyr::filter(Stock == stk) %>%
            select(Year,Spn)
#head(test.df)

test.df.sub <- test.df %>% dplyr::filter(Year > calc.yr - yrs.do )
test.df.sub
```

```{r JAGS model running}
# JAGS VERSION
# use the MCMC jags version
est.jags <- calcPercChangeMCMC(vec.in = log(test.df.sub$Spn),
                   method = "jags",
                   model.in = NULL, # this defaults to the BUGS code in the built in function trend.bugs.1()
                   perc.change.bm = -25,
                   out.type = "long",
                   mcmc.plots = FALSE,
                   convergence.check = FALSE# ??Conv check crashes on ts() ???
                   )
est.jags$pchange
est.jags$probdecl
est.jags$summary
est.jags$slope.converged
est.jags$samples

plotPattern(yrs = test.df$Year ,vals = log(test.df$Spn),
            width=1,color="darkblue",
            yrs.axis=TRUE,vals.axis=TRUE,
            #vals.lim=c(10,14),
            hgrid=TRUE,vgrid=FALSE,
            pch.val=19,pch.bg=NULL)

addFit(data.df = test.df.sub, coeff = list(intercept = est.jags$summary["intercept","50%"],
                                       slope = est.jags$summary["slope","50%"] )
)


plotPattern(yrs = test.df.sub$Year ,vals = log(test.df.sub$Spn),
            width=1,color="darkblue",
            yrs.axis=TRUE,vals.axis=TRUE,
            #vals.lim=c(10,14),
            hgrid=TRUE,vgrid=FALSE,
            pch.val=19,pch.bg=NULL)

addFit(data.df = test.df.sub, coeff = list(intercept = est.jags$summary["intercept","50%"],
                                           slope = est.jags$summary["slope","50%"] )
)
```
